[package]
name = "httpserve"
version = "0.1.0"
authors = ["mosm <airman515@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
async-std = { version = "1.9.0", features = ["attributes"] }
futures = "0.3.13"
httparse = "1.3.6"
